### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by anmipo** [inputstick/InputStickAPI-iOS#3]
First of all, thank you for the great product!

I’d like to integrate InputStick with my iOS app, but it seems this repository does not have a license. And [no license](https://choosealicense.com/no-permission/) means no permissions granted, so I cannot use the API, unfortunately. 

Can you please add a license to the repository? Thanks!

**Comment by Fulgan** [comment]
*bumb* Having a clear license for a library is really necessary. Solving this would be of great help.

**Comment by keepassium** [comment]
@inputstick, any chance on clarifying this?

**Comment by DunklerPhoenix** [comment]
https://github.com/inputstick/InputStickAPI-iOS/commit/f39782b93ea812674cb5c00c612935adc0951d81

**Comment by keepassium** [comment]
@DunklerPhoenix , thanks for the heads-up!

**Comment by anmipo** [comment]
@DunklerPhoenix , thanks for the heads-up!
